import pickle

selected_qids = [
    21129, 18275, 26496, 25084, 20584, 24084, 19041, 21681, 21817, 25970, 19329,
    15816, 17959, 19851, 23861, 22153, 17657, 23620, 18659, 19921, 18732, 17503,
    16636, 26720, 16394, 21610, 22938, 22188, 23462
]

qids = [
    25084, 23861, 20615, 25970, 18587, 21986, 20584, 21681, 25362, 15816, 15743,
    23924, 24084, 15654, 22153, 16636, 21129, 25668, 22919, 16798, 16394, 26584,
    25235, 24584, 26216, 19116, 17503, 19329, 24583, 24227, 21817, 19041, 20304,
    21806, 26466, 18028, 26496, 22209, 21029, 17959, 19851, 23739, 25507, 19921,
    19833, 22938, 23649, 21347, 25489, 26006, 25548, 23561, 21117, 17881, 22077,
    20107, 16069, 18825, 24392, 18659, 26711, 24504, 16890, 19010, 23549, 18355,
    25075, 19824, 25091, 19819, 19255, 18732, 22367, 17212, 24780, 18275, 26720,
    24545, 21610, 17161, 22291, 23620, 22823, 24673, 16594, 22862, 23480, 23462,
    19853, 22188, 17698, 20617, 18906, 17657, 18467, 26246, 17448, 24367, 26706,
    25486
]

answers = [
    '{Belisarius}',
    '{Lydia} or {Lydian}s',
    'William Henry {Seward}',
    '{Franz Joseph} I of Austria',
    'Jack Cade',
    '{Prime Minister} of Israel [accept word forms, but do not accept any other positions like President of Israel]',
    'José de la Cruz Porfirio {Díaz} Mori [prompt on the {Old Dictator}]',
    '{Merovingians}',
    '{Joseph} {Knecht} (accept {Magister Ludi} or {Josephus III}) (3)',
    'Haiti',
    'South Africa',
    'Khrushchev Thaw',
    'John Nance {Garner}',
    'Iceland',
    'Song Dynasty',
    'Mamluks or Mamlukes',
    '{Babylon}',
    'Oswald Mosley',
    'Spain',
    'Gamal {Abdel Nasser}',
    'Sir Winston Leonard Spencer Churchill',
    'Annie Besant',
    '{Louis XIII} [prompt on {Louis}; accept {Louis le Juste}]',
    '{Louis IX} (prompt on “{Saint Louis}”)',
    'Article III of the United States Constitution',
    '{governor} of {California} [prompt on partial answer]',
    'Bosworth Field',
    'Marcus {Garvey}',
    '{Turkmenistan}',
    'U.S. {Constitutional Amendments} [prompt on {Amendments}before "U.S. Constitution"]',
    'Antonio de Oliveira {Salazar}',
    '{Han} Dynasty',
    'Republic of {Tunisia} [or {Al Jumhuriyah} at {Tunisiyah}]',
    '{Queretaro}',
    'First Crusade [anti-prompt on "People\'s Crusade" or "German Crusade"]',
    'Isabella of Castile or Isabella I or Isabella "The Catholic"',
    'Eleanor Roosevelt (accept Eleanor alone after "Roosevelt" is read)',
    '{Bay} of {Pigs} Invasion [or {Bahia} de {los Cochinos}]',
    '{Shays}\' Rebellion',
    'Yi or Choson Dynasty',
    'Battle of Hastings',
    '{Charles}',
    'Captain James Cook',
    '{Fugitive Slave} Acts',
    'Texas',
    'Missouri',
    'Gartner, Inc.',
    '{Franco}-{Prussian} War [or {Franco}-{German} War; or 1870 War]',
    '{Fatimid} Dynasty',
    '{Peter the Great} or {Peter I}.',
    '{muckraker}s',
    'New Netherlands (accept Nieuw Nederlandt, Nova Belgium, or Novum Belgium; do not accept "New Holland"; probably do not accept "New Amsterdam" because all the clues are pretty clearly about a colony)',
    'Islamic Republic of {Iran}',
    'Dalai Lama',
    'Battle of {Perryville} (or Battle of {Chaplin Hills}; prompt on "{Battle} for {Kentucky}")',
    'Giuseppe {Garibaldi}',
    'Giuseppe Garibaldi',
    'Mungo Park',
    '{Hanseatic League} [or {Hansa}]',
    'Wendell Phillips',
    'Rodrigo (Roa) Duterte [or Rody Duterte; accept Digong] &lt;BY/JR&gt;',
    'United States {Secretary of State}',
    'Battle of Bannockburn',
    'Battle of {Hastings}',
    '{shah} of Iran [or {shahanshah;} or {king of Iran;} accept {Pahlavi shahs} until \"Pahlavi\" is read]',
    'Martin Van Buren',
    'Theophile {Delcasse}',
    'Wars of the {Roses}',
    '{Quadruple} Alliance',
    'Wars of the {Roses}',
    '{Secretary} of the {Navy}',
    'Stamford Raffles',
    'Great {Northern} War [accept {Second Northern} War]',
    'James Earl "Jimmy" Carter, Jr.',
    'Battle of the {Java Sea}',
    'Aksum or Axum',
    'Seven Years’ War [prompt on French and Indian War until it’s mentioned] &lt;MK&gt;',
    'Anglo-Zulu War',
    'Treaty of {Tordesillas}',
    'Battle of Pavia',
    '{Syrian} Arab Republic',
    'Battle of {Solferino}',
    'Ivan III',
    'Alexander Stephens',
    'Indonesia',
    'Richard I [or Richard Coeur de Lion, or Richard the Lionhearted; prompt on Richard]',
    'Vichy France or Vichy government [accept French State or l\'État français]',
    'Valley Forge',
    'Battle of Hastings',
    'Peace of {Westphalia}',
    'Munich',
    'Sir Francis {Drake}',
    'George {Herbert Walker Bush} (accept {Bush Sr.} or {Bush 41} or whatever)',
    'Yitzhak Rabin',
    'Robert Bork',
    'Tenochtitlan',
    'William Jennings Bryan',
    'Treaty of {Tilsit}',
    'the assassination of Abraham Lincoln [accept obvious equivalents]',
    '{Second Crusade}',
]

questions = [
    'though he was recalled ten years later to repel a Bulgarian invasion of Constantinople.',
    'Though it flourished under the rule of such Mermnad kings as Sadyattes and Alyattes II',
    'then switched to the Whig Party as governor of New York from 1839 to 1843.',
    'Austro-Hungarian emperor whose long reign lasted from 1848-1916 and whose nephew was Franz Ferdinand.',
    'in 1450 he settled in Kent posing as a doctor named John Aylmer',
    'The unilateral withdrawal of Israeli forces from the Gaza Strip was authorized by Ariel Sharon',
    'dictator who ruled Mexico almost continuously from 1876 until 1911.',
    'Their princesses like Bathilde and Burgundofara often become abbesses and this dynasty ended when Pope Zachary deposed Childeric III',
    'he interacts with minor characters such as Bastian Perrot and Bertram.',
    'Caribbean island nation whose independence movement against France was led by Toussaint L\'Ouverture.',
    'An individual from this country was likely responsible for the Dulcie September shooting in Paris',
    'to the 20th Communist party Congress',
    'name Texan, nicknamed "Cactus Jack, who was the first vice president for FDR.',
    '570  miles west of Norway, it is separated from Greenland by the 155­mile­wide Denmark Strait.',
    'This dynasty was founded by Zhao Kuangyin (kwang-YIN)',
    'military caste of Islamic slaves who ruled Egypt from 1250 to 1517.',
    'This city\'s dynasties included the Kassites. Its surrounding empire won at Carchemish centuries after Tigliath-Pilaser',
    'the daughter of former Viceroy of India George Curzon.',
    'home to Isaac Albeniz and thecomposer of Love the Magician and The Three-Cornered Hat',
    'though Abdel Qasim\'s defeat of al-Shawaf in Iraq led to further persecution of Communists.',
    'man who succeeded Neville Chamberlain as Prime Minister of Britain during World War II.',
    'Blavatsky converted this woman to the Theosophical Society, of which she became the second president.',
    'This ruler commissioned Theophraste Renaudot to open the first newspaper in France.',
    'The main rival of this son of Blanche of Castile was Henry III of England',
    'Section 3 of this Constitutional article was reviewed in 1945\'s Cramer v. United States',
    'Brown was defeated four years later by Ronald Reagan',
    'battle of 1485 in which Richard III was slain and Henry Tudor was crowned',
    'He was elected the "Provisional President of Africa" at a 1920 convention in Liberty Hall.',
    'Reporters Without Borders claimed in 2005 that it had the second worst press freedom conditions in the world',
    'the first ten of which make up the Bill of Rights?',
    'Prime Minister from 1932 to 1968 who presided over the Estado Novo in Portugal.',
    'early Chinese dynasty founded by Liu Bang following the collapse of the Qin Dynasty.',
    'North African nation that ousted Zinedine Ben Ali (ZIN-uh-deen) in January 2011.',
    'This region\'s ancient history saw inhabitants named the Otomi build cities at Ranas and El Cerrito; later',
    'One campaign during this war was ambushed at Civetot and led by Peter the Hermit.',
    'The second child of Juan II and the successor to a half-brother Enrique IV',
    'This first chair of the UN Commission on Human Rights helped develop the Universal Declaration of Human Rights',
    'failed CIA backed invasion of Cuba ordered by John F. Kennedy.',
    'John Bly and Charles Rose were the only two men hanged for their role in this event.',
    'house founded by King Taejo that ruled from 1392 to 1910',
    '1066 victory for Norman invaders led by William the Conqueror.',
    'One ruler with this first name was advised by the Count of Floridablanca',
    'while Herman Sporing and Daniel Solander were naturalists on one of his voyages.',
    'Daniel Webster\'s "Seventh of March" speech controversially supported the second of these acts',
    'second-largest U.S. state with capital Austin.',
    'state which was admitted to the Union with Maine in an 1820 compromise named after it.',
    'In 2005 this company acquired the Burton Group and the Meta Group.',
    'this war saw one side led by Marshal Achille Bazaine inflict heavy casualties at the Battle of Gravelotte',
    'Turkish general al-Basasiri handed control of Baghdad to this caliphate',
    'man who defeated Sweden\'s Charles XII at the 1709 Battle of Poltava',
    'more prominent ones included Shame of the Cities author Lincoln Steffens and Standard Oil denouncer Ida Tarbell.',
    'a territory centered on New Amsterdam in present-day New York.',
    'country formerly ruled by Ayatollah Kohmeni where 52 American were held hostage from 1979-1981.',
    'the 1989 Nobel Peace Prize was awarded to the exiled fourteenth spiritual head of Buddhist Tibet.',
    'Jefferson C. Davis shot and killed Bull Nelson at the Galt House Hotel',
    'This man lost his wife Anita on the run from Austrian and French forces',
    'this man fought with varying success while outnumbered at Luino and Morazzone before retreating to Switzerland.',
    'he was held captive by an Arab chief for four months; on the second',
    'Heinrich Sudermann filled the new post of Syndic and tried to revive its power in later years.',
    'who became the president of the American Anti-Slavery Society after Garrison.',
    'This man recently cancelled peace negotiations with a coalition in this country abbreviated CPP–NDA–NDF.',
    'was appointed by Washington and notably opposed the views of the Treasury Secretary Alexander Hamilton',
    '1314 battle in which Robert the Bruce defeated Edward II and established Scottish independence.',
    'which 1066 battle that saw Harold Godwinsson suffer defeat at the hands of William the Conqueror?',
    'national monarch overthrown by Ayatollah Khomeini in the 1979 Iranian Revolution.',
    'later served two terms in the state senate before becoming a US Senator in 1821',
    'French foreign minister during the Fashoda crisis and the early 20th century.',
    'saw Edward IV defeat the forces of Margaret of Anjou.',
    'The second one was formed in 1815 to regulate European politics after the fall of Napoleon',
    'This conflict included the defeat and beheading of Henry Beaufort by John Neville at the Battle of Hexham.',
    'Before ending the Second Bank of the United States as Jackson\'s Secretary of the Treasury',
    'when Lord Hastings charged him with creating a fortified British port on the Strait of Malacca.',
    'One participant in it won the Battle of Pruth River before negotiating for control of Azov',
    'Democratic President who lost the 1980 election to Ronald Reagan.',
    'Japan\'s Long Lance torpedo devastated the ABDA fleet and sunk the flagship De Ruyter',
    'Yet it is most famed for Ezana\'s decision to follow Frumentius\' advice and convert to Christianity.',
    'twelve Mingo warriors helped win the Battle of Jumonville Glen.',
    '1879 war between the United Kingdom and a South African kingdomruled by such men as Cetshwayo and Shaka.',
    '1494 agreement that established a line of demarcation between Spanish and Portuguese conquests in the New World.',
    'battle by which Charles V solidified Spanish hegemony at the climax of the Italian Wars in 1525.',
    'opposed this country\'s 1964 federation with Egypt to form the United Arab Republic.',
    'combined victory for Napoleon III and the Piedmontese fought in Lombardy',
    'was the subjugation of Novgorod in 1478 and the acquisition of the territories of Pskov and Tver.',
    'who was this Georgian who frequently opposed Jefferson Davis as vice president of the Confederacy?',
    'This nation is home to the Buddhist monuments of Borobudur and Prambanan.',
    'English King who succeeded to the throne after the death of Henry II and captured the city of Acre',
    'French government which collaborated with Nazi Germany during World War II.',
    'Pennsylvania valley where George Washington\'s troops suffered through the winter of 1777.',
    '1066 victory for William the Conqueror, a decisive battle in the Norman conquest of England.',
    'identify this 1648 treaty that upheld the Peace of Augsburg and ended the Thirty Years War.',
    'what city known for its Hofbrauhaus and celebration of Oktoberfest is the capital of Bavaria?',
    'In 1567, he commanded the Judith on John HawkinsÕs expedition to the Gulf of Mexico.',
    'Officials retained from his predecessor include press secretary Marlin Fitzwater and Treasury Secretary Nicholas Brady',
    'He thus earned a 1994 Nobel Peace Prize and a 1995 assassination by Yigal Amir.',
    'After Elliot Richardson and William Ruckelshaus resigned over the issue of firing Special Prosecutor Archibald Cox',
    'located on an island in Lake Texcoco and destroyed in 1521 by Hernán Cortés.',
    'populist from Nebraska who participated in the Scopes trial and delivered the "Cross of Gold" speech.',
    'King Frederick William III of Prussia took part and the puppet Kingdom of Westphalia was created.',
    'what event occurred when John Wilkes Booth shot the 16th president of America?',
    'Conrad III allied with Manuel Comnenus against Roger of Sicily',
]

print(len(selected_qids))

flashcards = []
for i, qid in enumerate(qids):
    if qid not in selected_qids:
        continue
    flashcards.append({
        'text': questions[i],
        'user_id': 'matthew',
        'question_id': qids[i],
        'label': 'null',
        'answer': answers[i],
        })
print('# flashcards', len(flashcards))
print()

with open('matthew_card_set.pkl', 'wb') as f:
    pickle.dump(flashcards, f)
