"""save recall target in schedule request

Revision ID: 24b6a54c532e
Revises: 394b97f6c2dd
Create Date: 2022-08-05 03:21:55.783370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b6a54c532e'
down_revision = '394b97f6c2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedulerequest', sa.Column('recall_target', sa.Float(), nullable=True))
    op.add_column('schedulerequest', sa.Column('recall_target_lowest', sa.Float(), nullable=True))
    op.add_column('schedulerequest', sa.Column('recall_target_highest', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedulerequest', 'recall_target_highest')
    op.drop_column('schedulerequest', 'recall_target_lowest')
    op.drop_column('schedulerequest', 'recall_target')
    # ### end Alembic commands ###
