"""try autogenerate

Revision ID: 34c479b627d1
Revises: d36e91f88408
Create Date: 2022-08-03 03:51:40.882462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34c479b627d1'
down_revision = 'd36e91f88408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_currcardfeaturevector_card_id', table_name='cardfeaturevector')
    op.create_index(op.f('ix_cardfeaturevector_card_id'), 'cardfeaturevector', ['card_id'], unique=False)
    op.drop_constraint('cardsnapshot_id_fkey', 'cardsnapshot', type_='foreignkey')
    op.create_foreign_key(None, 'cardsnapshot', 'schedulerequest', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('record_card_id_fkey', 'record', type_='foreignkey')
    op.drop_constraint('record_user_id_fkey', 'record', type_='foreignkey')
    op.create_foreign_key(None, 'record', 'card', ['card_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'record', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('schedulerequest', 'card_ids',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.drop_index('ix_currusercardfeaturevector_card_id', table_name='usercardfeaturevector')
    op.drop_index('ix_currusercardfeaturevector_user_id', table_name='usercardfeaturevector')
    op.create_index(op.f('ix_usercardfeaturevector_card_id'), 'usercardfeaturevector', ['card_id'], unique=False)
    op.create_index(op.f('ix_usercardfeaturevector_user_id'), 'usercardfeaturevector', ['user_id'], unique=False)
    op.drop_index('ix_curruserfeaturevector_user_id', table_name='userfeaturevector')
    op.create_index(op.f('ix_userfeaturevector_user_id'), 'userfeaturevector', ['user_id'], unique=False)
    op.drop_constraint('usersnapshot_id_fkey', 'usersnapshot', type_='foreignkey')
    op.create_foreign_key(None, 'usersnapshot', 'schedulerequest', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('userstatsv2_user_id_fkey', 'userstatsv2', type_='foreignkey')
    op.create_foreign_key(None, 'userstatsv2', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userstatsv2', type_='foreignkey')
    op.create_foreign_key('userstatsv2_user_id_fkey', 'userstatsv2', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'usersnapshot', type_='foreignkey')
    op.create_foreign_key('usersnapshot_id_fkey', 'usersnapshot', 'schedulerequest', ['id'], ['id'])
    op.drop_index(op.f('ix_userfeaturevector_user_id'), table_name='userfeaturevector')
    op.create_index('ix_curruserfeaturevector_user_id', 'userfeaturevector', ['user_id'], unique=False)
    op.drop_index(op.f('ix_usercardfeaturevector_user_id'), table_name='usercardfeaturevector')
    op.drop_index(op.f('ix_usercardfeaturevector_card_id'), table_name='usercardfeaturevector')
    op.create_index('ix_currusercardfeaturevector_user_id', 'usercardfeaturevector', ['user_id'], unique=False)
    op.create_index('ix_currusercardfeaturevector_card_id', 'usercardfeaturevector', ['card_id'], unique=False)
    op.alter_column('schedulerequest', 'card_ids',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.create_foreign_key('record_user_id_fkey', 'record', 'user', ['user_id'], ['id'])
    op.create_foreign_key('record_card_id_fkey', 'record', 'card', ['card_id'], ['id'])
    op.drop_constraint(None, 'cardsnapshot', type_='foreignkey')
    op.create_foreign_key('cardsnapshot_id_fkey', 'cardsnapshot', 'schedulerequest', ['id'], ['id'])
    op.drop_index(op.f('ix_cardfeaturevector_card_id'), table_name='cardfeaturevector')
    op.create_index('ix_currcardfeaturevector_card_id', 'cardfeaturevector', ['card_id'], unique=False)
    # ### end Alembic commands ###
