"""default values

Revision ID: df41c0069528
Revises: e56c7509d015
Create Date: 2022-08-04 17:58:51.480434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df41c0069528'
down_revision = 'e56c7509d015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cardfeaturevector', 'count_positive',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cardfeaturevector', 'count_negative',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cardfeaturevector', 'count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usercardfeaturevector', 'count_positive',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usercardfeaturevector', 'count_negative',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usercardfeaturevector', 'count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usercardfeaturevector', 'count_positive_session',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usercardfeaturevector', 'count_negative_session',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usercardfeaturevector', 'count_session',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('userfeaturevector', 'count_positive',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('userfeaturevector', 'count_negative',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('userfeaturevector', 'count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('userfeaturevector', 'count_positive_session',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('userfeaturevector', 'count_negative_session',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('userfeaturevector', 'count_session',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('userfeaturevector', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userfeaturevector', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('userfeaturevector', 'count_session',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('userfeaturevector', 'count_negative_session',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('userfeaturevector', 'count_positive_session',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('userfeaturevector', 'count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('userfeaturevector', 'count_negative',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('userfeaturevector', 'count_positive',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usercardfeaturevector', 'count_session',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usercardfeaturevector', 'count_negative_session',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usercardfeaturevector', 'count_positive_session',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usercardfeaturevector', 'count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usercardfeaturevector', 'count_negative',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usercardfeaturevector', 'count_positive',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cardfeaturevector', 'count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cardfeaturevector', 'count_negative',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cardfeaturevector', 'count_positive',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
