"""remove old record

Revision ID: e56c7509d015
Revises: d8d564bfa1b7
Create Date: 2022-08-03 04:40:57.955083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56c7509d015'
down_revision = 'd8d564bfa1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cardsnapshot_id_fkey', 'cardsnapshot', type_='foreignkey')
    op.create_foreign_key(None, 'cardsnapshot', 'schedulerequest', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cardsnapshot', type_='foreignkey')
    op.create_foreign_key('cardsnapshot_id_fkey', 'cardsnapshot', 'schedulerequest', ['id'], ['id'])
    # ### end Alembic commands ###
