"""typed and recommendation

Revision ID: e5e098cee8ca
Revises: 53a244f1fc99
Create Date: 2022-08-05 04:51:34.015832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e098cee8ca'
down_revision = '53a244f1fc99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studyrecord', sa.Column('typed', sa.String(), nullable=True))
    op.add_column('studyrecord', sa.Column('recommendation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studyrecord', 'recommendation')
    op.drop_column('studyrecord', 'typed')
    # ### end Alembic commands ###
