"""snapshot v2 wip

Revision ID: f34513de26e2
Revises: e5e098cee8ca
Create Date: 2022-08-05 14:47:23.004250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34513de26e2'
down_revision = 'e5e098cee8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
